name: flutter_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

#-- package --#
dependencies:
  flutter:
    sdk: flutter

  #utily pacakge


  #icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  #state management
  get: ^4.6.6

  #product specific


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #-- local assets --#
  assets:
    - assets/

  #-- local fonts --#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/
